### ISSUE TITLE
Error on facebook.auth.getSession()

### ISSUE THREAD

**Issue by Okram87** [sciyoshi/pyfacebook#25]
I've used pyFacebook for weeks without any problem, but since this week every time I call
facebook.auth.getSession()
I receive this error:

Traceback (most recent call last):
  File "../file.py", line 27, in nameFile
    facebook.auth.getSession()
  File "../pyFacebook/Facebook.py", line 669, in getSession
    result = self._client('%s.getSession' % self._name, args)
  File "../pyFacebook/Facebook.py", line 1110, in __call__
    return self._parse_response(response, method)
  File "../pyFacebook/Facebook.py", line 1047, in _parse_response
    self._check_error(result)
  File "../pyFacebook/Facebook.py", line 998, in _check_error
    raise FacebookError(response['error_code'], response['error_msg'], response['request_args'])
pyFacebook.Facebook.FacebookError: Error 100: Invalid parameter

Anyone can help me?
Thank you

**Comment by ljluestc** [comment]
```
try:
    # Ensure that you have a valid access token before calling getSession
    if valid_access_token:
        session = facebook.auth.getSession(access_token=valid_access_token)
        # Process the session data as needed
    else:
        print("Invalid access token")
except facebook.FacebookError as e:
    print(f"Facebook API error: {e}")
    # Handle the error gracefully

```
