### ISSUE TITLE
Value Error

### ISSUE THREAD

**Issue by nooscraft** [sciyoshi/pyfacebook#45]
Traceback (most recent call last):

  File "C:\Python26\lib\site-packages\django\core\servers\basehttp.py", line 279, in run
    self.result = application(self.environ, self.start_response)

  File "C:\Python26\lib\site-packages\django\core\servers\basehttp.py", line 651, in **call**
    return self.application(environ, start_response)

  File "C:\Python26\lib\site-packages\django\core\handlers\wsgi.py", line 241, in **call**
    response = self.get_response(request)

  File "C:\Python26\lib\site-packages\django\core\handlers\base.py", line 73, in get_response
    response = middleware_method(request)

  File "build\bdist.win32\egg\socialregistration\middleware.py", line 13, in process_request
    request.facebook.check_session(request)

  File "C:\Python26\lib\site-packages\facebook__init__.py", line 1293, in check_session
    self.session_key_expires = int(params['expires'])

ValueError: invalid literal for int() with base 10: 'None'

**Comment by ljluestc** [comment]
```
class Facebook:
    def check_session(self, request):
        params = request.GET
        if 'session' in params:
            self.session_key = params['session_key']
            self.uid = int(params['uid'])
            self.session_key_expires = None
            if 'expires' in params and params['expires'] != 'None':
                try:
                    self.session_key_expires = int(params['expires'])
                except ValueError:
                    # Handle the case where params['expires'] is not a valid integer
                    # You can choose to log this error or handle it differently based on your requirements
                    pass
        else:
            self.session_key = None
            self.uid = None
            self.session_key_expires = None

```
